version: "3.7"

services:
  api:
    build: ./server
    env_file: server/.env
    volumes: ["./server:/app/server"]
    expose:
      - 5000
    depends_on:
      - database
    ports:
      - 5000:5000

  client:
    ports:
      - 3000:3000
    build: ./client
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_SERVICE_URL=http://localhost:8080
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api

  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  database-data:
