"""Change timestamp

Revision ID: e6b3e103b87b
Revises: 63f962a7bc20
Create Date: 2020-07-03 14:38:15.567021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6b3e103b87b'
down_revision = '63f962a7bc20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('links', sa.Column('updated', sa.DateTime(), nullable=True))
    op.drop_column('links', 'updated_at')
    op.drop_column('links', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('created_at', postgresql.TIMESTAMP(
    ), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('links', sa.Column('updated_at', postgresql.TIMESTAMP(
    ), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('links', 'updated')
    op.drop_column('links', 'created')
    # ### end Alembic commands ###
